---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chipster-nginx-test
  labels:
    app: chipster-nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chipster-nginx-test
      deployment: chipster-nginx-test
  template:
    metadata:
      labels:
        app: chipster-nginx-test
        deployment: chipster-nginx-test
    spec:
      securityContext: {}
      containers:
        - name: chipster-nginx-test
          securityContext: {}
          image: {{ $.Values.image.name }}:{{$.Values.image.tag}}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
          resources: {}
