---
# http/websocket reverse proxy for making nginx accessible
# from the internet
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: chipster-nginx-test
  labels:
    app: chipster-nginx-test
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: chipster-nginx-test
          port: 80
