apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: base
  name: base
spec:
  output:
    to:
      kind: ImageStreamTag
      name: base:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: ""
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: base-24-04:latest
    type: Docker
  triggers:
    - type: ConfigChange
  # this seems to start an extra build when we have just run it
  # - imageChange:
  #   type: ImageChange
