filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /opt/chipster-web-server/logs/chipster.log

output.logstash:
  hosts: ["logstash:5044"]
# output.console:
#   pretty: true

# processors:
#   #- add_cloud_metadata: ~
#   - decode_json_fields:
#       fields: ["message"]
#       process_array: false
#       max_depth: 1
#       target: ""
#       overwrite_keys: true

