apiVersion: v1
kind: Template
metadata:
  name: ${NAME}-api
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: chipster${SUBPROJECT_POSTFIX}
      subproject: ${{SUBPROJECT}}
    name: ${NAME}${SUBPROJECT_POSTFIX}
  spec:
    host: ${NAME}${SUBPROJECT_POSTFIX}-${PROJECT}.${DOMAIN}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}${SUBPROJECT_POSTFIX}
      weight: 100
    wildcardPolicy: None
    
parameters:
- name: NAME
- name: PROJECT
- name: DOMAIN
- name: SUBPROJECT
- name: SUBPROJECT_POSTFIX
