apiVersion: v1
kind: Template
metadata:
  name: ${NAME}-api
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: chipster${SUBPROJECT_POSTFIX}
      subproject: ${{SUBPROJECT}}
    name: ${NAME}${SUBPROJECT_POSTFIX}
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: api
    selector:
      name: ${NAME}${SUBPROJECT_POSTFIX}
    sessionAffinity: None
    type: ClusterIP
    
parameters:
- name: NAME
- name: PROJECT
- name: DOMAIN
- name: SUBPROJECT
- name: SUBPROJECT_POSTFIX
