apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}-admin
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: chipster${SUBPROJECT_POSTFIX}
      subproject: ${{SUBPROJECT}}
    name: ${NAME}-admin${SUBPROJECT_POSTFIX}
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: admin
    selector:
      name: ${NAME}${SUBPROJECT_POSTFIX}
    sessionAffinity: None
    type: ClusterIP
    
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: chipster${SUBPROJECT_POSTFIX}
      subproject: ${{SUBPROJECT}}
    name: ${NAME}-admin${SUBPROJECT_POSTFIX}
  spec:
    host: ${NAME}-admin${SUBPROJECT_POSTFIX}-${PROJECT}.${DOMAIN}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}-admin${SUBPROJECT_POSTFIX}
      weight: 100
    wildcardPolicy: None

parameters:
- name: NAME
- name: PROJECT
- name: DOMAIN
- name: SUBPROJECT
- name: SUBPROJECT_POSTFIX
