# Chipster CI/CD configuration
#

include:
  # - gitlab/pipelines/build/gitlab-ci-build-base.yml
  - gitlab/pipelines/build/gitlab-ci-build.yml
  # - gitlab/pipelines/build/gitlab-ci-build-comp.yml
  - gitlab/pipelines/test/gitlab-ci-test.yml
stages:
  # - build-base
  - build
  # - build-comp
  - test
  - csc

trigger_job:
  stage: csc
  variables:
    PARENT_CI_PIPELINE_CREATED_AT: $CI_PIPELINE_CREATED_AT
  trigger:
    project: chipster/chipster-csc
    branch: $CI_COMMIT_BRANCH
