# Chipster CI/CD configuration
#

variables:
  RUN_BASE_BUILDS:
    value: false
    options:
      - true
      - false
    description: "Run base builds."
  RUN_COMP_BUILDS:
    value: false
    options:
      - true
      - false
    description: "Run comp builds."

include:
  - local: gitlab/pipelines/build/gitlab-ci-build-base.yml
    rules:
      - if: $RUN_BASE_BUILDS == true
  - local: gitlab/pipelines/build/gitlab-ci-build.yml
  - local: gitlab/pipelines/build/gitlab-ci-build-comp.yml
    rules:
      - if: $RUN_COMP_BUILDS == true
  - local: gitlab/pipelines/test/gitlab-ci-test.yml
stages:
  - build-base
  - build
  - build-comp
  - test
  - csc

trigger_job:
  stage: csc
  variables:
    PARENT_CI_PIPELINE_CREATED_AT: $CI_PIPELINE_CREATED_AT
  trigger:
    project: chipster/chipster-csc
    branch: $CI_COMMIT_BRANCH
