apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: comp-r-4-2-3-cellbender
  name: comp-r-4-2-3-cellbender
spec:
  output:
    to:
      kind: ImageStreamTag
      name: comp-r-4-2-3-cellbender:latest
  postCommit: {}
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 500Mi
  runPolicy: Serial
  source:
    dockerfile: ""
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: comp-r-4-2-3:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
    - imageChange:
      type: ImageChange
