apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: base-ci-test
  name: base-ci-test
spec:
  output:
    to:
      kind: ImageStreamTag
      name: base-ci-test:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: ""
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: base-java-utils:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
    - imageChange:
      type: ImageChange
