apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: cli-client
  name: cli-client
spec:
  output:
    to:
      kind: ImageStreamTag
      name: cli-client:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: ""
    git:
      ref: master
      uri: https://github.com/chipster/chipster-web-server.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: base-node:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange:
    type: ImageChange
