#!/usr/bin/env python3

import os
import yaml
import sys

def get_needs(buildconfig, build_name):
    base_image = buildconfig["spec"]["strategy"]["dockerStrategy"]["from"]["name"]

    base_image_name, base_image_tag = base_image.split(":", 1)

    needs = []

    if base_image_tag == "latest":
        needs.append("build-" + base_image_name)
    else:
        print("build '" + build_name + "' has base imamge tag '" + base_image_tag + "'. Assuming this is an external image")

    source = buildconfig["spec"]["source"]

    if "images" in source:
        source_images = source["images"]

        for source_image_dict in source_images:
            image_from = source_image_dict["from"]["name"]

            source_image_name, source_image_tag = image_from.split(":", 1)

            if source_image_tag == "latest":
                needs.append("build-" + source_image_name)
            else:
                print("build '" + build_name + "' has source image tag '" + source_image_tag + "'. Assuming this is an external image")

    # remove duplicates
    return list(set(needs))

def get_gitlab_ci(path):

    gitlab_ci = {
        "stages": ["build", "test"],

        "db_name": {
            "stage": "test",
            "script": [
                "echo DB_NAME=postgres_$(echo $CI_PIPELINE_CREATED_AT | tr ':' '-') >> build.env"
            ],
            "artifacts": {
                "reports": {
                    "dotenv": "build.env"
                }
            }
        },
        "ci-test": {
            "stage": "test",
            "needs": [
                "db_name"
            ],
            "script": [
                ""
                "sudo docker run --detach -e POSTGRES_PASSWORD=chipster -e POSTGRES_USER=user --name $DB_NAME postgres:14",
                "sudo docker run -e PGPASSWORD=chipster --link $DB_NAME postgres:14 createdb -h $DB_NAME -U user auth_db ",
                "sudo docker run -e PGPASSWORD=chipster --link $DB_NAME postgres:14 createdb -h $DB_NAME -U user session_db_db ",
                "sudo docker run -e PGPASSWORD=chipster --link $DB_NAME postgres:14 createdb -h $DB_NAME -U user job_history_db ",
                "sudo docker run \
-e db_pass_auth=chipster \
-e db_url_auth=jdbc:postgresql://$DB_NAME:5432/auth_db  \
-e db_url_session_db=jdbc:postgresql://$DB_NAME:5432/session_db_db  \
-e db_url_job_history=jdbc:postgresql://$DB_NAME:5432/job_history_db  \
--link $DB_NAME image-registry.apps.2.rahti.csc.fi/chipster-images-dev/chipster-web-server java \
-cp lib/*: fi.csc.chipster.rest.ServerLauncher"
                # "sudo docker stop " + pg_name,
                # "sudo docker rm " + pg_name,
            ]
        } 
    }
    
    dir_list = os.listdir(path)
    for buildDir in dir_list:

        if not os.path.isdir(path + "//" + buildDir):
            continue

        with open(path + "//" + buildDir + "//" + buildDir + ".yaml", "r") as buildconfig_file:
            buildconfig = yaml.safe_load(buildconfig_file)

            needs = get_needs(buildconfig, buildDir)

            gitlab_ci["build-" + buildDir] = {
                "stage": "build",
                "needs": needs,
                "script": [
                    "cd gitlab", "bash build-image-ci.bash " + buildDir + " $CI_PIPELINE_CREATED_AT"
                ]
            }
    return gitlab_ci

def main() -> int:
    gitlab_ci = get_gitlab_ci("..//..//kustomize//builds")

    header = """
# Chipster CI/CD configuration
# 
# Do not edit this file! Make changes in BuildConfigs under kustomize/builds and run
# 
# cd gitlab/generate-gitlab-ci
# python3 -m venv venv
# source venv/bin/activate
# pip3 install -r requirements.txt
# ./generate-gitlab-ci.py
# 

"""

    with open("..//..//.gitlab-ci.yml", 'w') as file:
        file.write(header)
        yaml.dump(gitlab_ci, file)

    # print(header)
    # print(yaml.dump(gitlab_ci))
    return 0

if __name__ == '__main__':
    sys.exit(main())




                    