apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: chipster-web-server-build
  name: chipster-web-server-build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: chipster-web-server-build:latest
  postCommit: {}
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1Gi
  runPolicy: Serial
  source:
    dockerfile: ""
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: chipster-web-server:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
