deployments:
  webServer:
    name: web-server
    class: ""
    image: web-server
    apiPort: 8000
    adminPort: 8100
    eventsPort: ""
    workDir: /opt/chipster
    password: web-server
  auth:
    name: auth
    class: fi.csc.chipster.auth.AuthenticationService
    image: chipster-web-server
    apiPort: 8002
    adminPort: 8102
    eventsPort: ""
    workDir: /opt/chipster
    password: auth
  serviceLocator:
    name: service-locator
    class: fi.csc.chipster.servicelocator.ServiceLocator
    image: chipster-web-server
    apiPort: 8003
    adminPort: 8103
    eventsPort: ""
    workDir: /opt/chipster
    password: service-locator
  sessionDb:
    name: session-db
    class: fi.csc.chipster.sessiondb.SessionDb
    image: chipster-web-server
    apiPort: 8004
    adminPort: 8104
    eventsPort: 8005
    workDir: /opt/chipster
    password: session-db
  scheduler:
    name: scheduler
    class: fi.csc.chipster.scheduler.Scheduler
    image: chipster-web-server
    apiPort: 8006
    adminPort: 8106
    eventsPort: ""
    workDir: /opt/chipster
    password: scheduler
  fileBroker:
    name: file-broker
    class: fi.csc.chipster.filebroker.FileBroker
    image: chipster-web-server
    apiPort: 8007
    adminPort: 8107
    eventsPort: ""
    workDir: /opt/chipster
    password: file-broker
  toolbox:
    name: toolbox
    class: ""
    image: toolbox
    apiPort: 8008
    adminPort: 8108    
    eventsPort: ""
    workDir: /opt/chipster/toolbox
    password: toolbox
  sessionWorker:
    name: session-worker
    class: fi.csc.chipster.sessionworker.SessionWorker
    image: chipster-web-server
    apiPort: 8009
    adminPort: 8109
    eventsPort: ""
    workDir: /opt/chipster
    password: session-worker
  typeService:
    name: type-service
    class: ""
    image: chipster-web-server-js
    apiPort: 8010
    adminPort: 8110
    eventsPort: ""
    workDir: /opt/chipster
    password: type-service
  comp:
    name: comp
    class: comp
    image: comp
    apiPort: ""
    adminPort: 8111
    eventsPort: ""
    workDir: /opt/chipster/comp
    password: comp
  backup:
    name: backup
    class: fi.csc.chipster.backup.Backup
    image: chipster-web-server
    apiPort: ""
    adminPort: 8115
    eventsPort: ""
    workDir: /opt/chipster
    password: backup
  jobHistory:
    name: job-history
    class: fi.csc.chipster.jobhistory.JobHistoryService
    image: chipster-web-server
    apiPort: ""
    adminPort: 8114
    eventsPort: ""
    workDir: /opt/chipster
    password: job-history

databases:
  auth:
    password: "auth-postgresql"
  sessionDb:
    password: "session-db-postgresql"
  jobHistory:
    password: "job-history-postgresql"

users:
  chipster:
    password: ""
  admin:
    password: ""
  example_session_owner:
    password: ""
  support_session_owner:
    password: ""

tokens:
  auth:
    privateKey:
  sessionDb:
    privateKey:
