apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${{NAME}}
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: ${{NAME}}
    spec:
      parallelism: 1
      completions: 1
      template:
        metadata:
          name: ${{NAME}}
        spec:
          containers:
            - env:
                - name: TOOLS_BIN_VERSION
                  value: ${{TOOLS_BIN_VERSION}}
              name: ${{NAME}}
              image: image-registry.openshift-image-registry.svc:5000/chipster/base
              command: ["bash", "-c", ""]
              resources:
                limits:
                  cpu: ${{CPU}}
                  memory: 8Gi
                requests:
                  cpu: ${{CPU}}
                  memory: 8Gi
              volumeMounts:
                - mountPath: /mnt/tools
                  name: tools-bin
                - mountPath: /mnt/temp
                  name: temp
          volumes:
            - name: tools-bin
              persistentVolumeClaim:
                claimName: tools-bin-${TOOLS_BIN_VERSION}
            - name: temp
              emptyDir: {}
          restartPolicy: OnFailure
parameters:
  - name: TOOLS_BIN_VERSION
  - name: NAME
  - name: CPU
