apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
objects:
  - apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    metadata:
      # annotations:
      #   volume.beta.kubernetes.io/storage-class: ${{STORAGE_CLASS}}
      name: ${{NAME}}
    spec:
      accessModes:
        - "ReadWriteMany"
      resources:
        requests:
          storage: ${{SIZE}}
parameters:
  - name: NAME
  - name: SIZE
  - name: STORAGE_CLASS
