- name: Install jq for parsing json
  apt:
    name: jq

- name: Install diceware for generating human friendly passwords
  apt:
    name: diceware

- name: Install community.general collection to use snap module
  shell: ansible-galaxy collection install community.general

- name: Install yq for parsing yaml files
  community.general.snap:
    name:
      - yq

- name: Install aws-cli for checking tools-bin versions
  community.general.snap:
    name:
      - aws-cli
