- name: Install jq for parsing json
  apt:
    name: jq

- name: Install diceware for generating human friendly passwords
  apt:
    name: diceware

- name: Install yq for parsing yaml files
  # no snap module in apt package "ansible-core" (would be in "ansible")
  shell: "snap install yq"

- name: Install aws-cli for checking tools-bin versions
  shell: "snap install aws-cli --classic"
