- name: Install jq for parsing json
  apt:
    name: jq

- name: Install diceware for generating human friendly passwords
  apt:
    name: diceware

- name: Install yq for parsing yaml files
  # no snap module in this ancient Ansible 2.0
  shell: "snap install yq"