{
 "title": "Benchmark",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "custom_interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Post",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "repeat": "threads",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$custom_interval" ], "type": "time" },
      { "params": [ "threads" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/post.*/",
     "query": "SELECT mean(\"value\") FROM /post.*/ WHERE (\"threads\" =~ /^$threads$/) AND $timeFilter GROUP BY time($__interval), \"threads\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Get",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$custom_interval" ], "type": "time" },
      { "params": [ "threads" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^get.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Get and put",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$custom_interval" ], "type": "time" },
      { "params": [ "threads" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/.*put.*/",
     "query": "SELECT mean(\"value\") FROM /post.*/ WHERE (\"threads\" =~ /^$threads$/) AND $timeFilter GROUP BY time($__interval), \"threads\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Delete",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$custom_interval" ], "type": "time" },
      { "params": [ "threads" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/delete.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}