{
 "title": "Chipster containers",
 "time": { "from": "2020-06-16T12:56:07.374Z", "to": "2020-06-16T13:26:07.374Z" },
 "templating": {
  "list": [
   {
    "name": "role",
    "query": "show tag values with key = \"role\""
   }
  ]
 },
 "panels": [
  {
   "title": "CPU $role",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "repeat": "role",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu.user",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu.system",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory $role",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "repeat": "role",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem.rss",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem.hierarchical_memory_limit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem.cache",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "Network IO $role",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "repeat": "role",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net.receive.bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net.transmit.bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO $role",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "repeat": "role",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read",
     "query": "SELECT derivative(mean(\"value\"), 1s) FROM \"disk.read\" WHERE (\"role\" =~ /^$role$/) AND $timeFilter GROUP BY time($__interval), \"id\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write",
     "query": "SELECT derivative(mean(\"value\"), 1s) FROM \"disk.write\" WHERE (\"role\" =~ /^$role$/) AND $timeFilter GROUP BY time($__interval), \"id\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk space $role",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "repeat": "role",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "fs" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diskFree",
     "query": "SELECT derivative(mean(\"value\"), 1s) FROM \"net.receive.bytes\" WHERE (\"role\" =~ /^$role$/) AND $timeFilter GROUP BY time($__interval), \"id\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "fs" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diskTotal",
     "query": "SELECT derivative(mean(\"value\"), 1s) FROM \"net.transmit.bytes\" WHERE (\"role\" =~ /^$role$/) AND $timeFilter GROUP BY time($__interval), \"id\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  }
 ]
}