apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: chipster-web
  name: chipster-web
spec:
  output:
    to:
      kind: ImageStreamTag
      name: chipster-web:latest
  postCommit: {}
  resources:
    limits:
      cpu: 2
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 4Gi
  runPolicy: Serial
  source:
    dockerfile: ""
    git:
      ref: master
      uri: https://github.com/chipster/chipster-web.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: base-node:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
    - imageChange:
      type: ImageChange
