---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: chipster
  name: auth-security
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: chipster
  name: db-backups
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---      
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: chipster
  name: grafana
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: chipster
  name: influxdb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: chipster
  name: logstash
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: chipster
  name: tools-bin-empty
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: chipster
  name: tools-bin-mylly
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: chipster
  name: replay-results
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi          
