{{- range $deploymentKey, $deployment := .Values.deployments }}
{{- if ne $deployment.name "service-locator" }}
{{- if ne $deployment.name "auth" }}
# Chipster configuration file for most of the Chipster services
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $deployment.name }}
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    url-int-service-locator: http://service-locator
    service-password-{{ $deployment.name }}: {{ $deployment.password | quote }}
    {{- if or (eq $deployment.name "session-db") (eq $deployment.name "backup")}}
    db-url-session-db: "jdbc:postgresql://session-db-postgres:5432/session_db_db"
    db-pass-session-db: {{ required "db.sessionDb.password is required" $.Values.db.sessionDb.password | quote }}
    {{- end }}
    {{- if or (eq $deployment.name "job-history") (eq $deployment.name "backup")}}
    db-url-job-history: "jdbc:postgresql://job-history-postgre:5432/job_history_db"
    db-pass-job-history: {{ required "db.jobHistory.password is required" $.Values.db.jobHistory.password | quote }}
    {{- end }}

    {{- if eq $deployment.name "backup"}}
    db-url-auth: "jdbc:postgresql://auth-postgres:5432/auth_db"
    db-pass-auth: {{ required "db.auth.password is requied" $.Values.db.auth.password | quote }}
    {{- end }}
    
    {{- if eq $deployment.name "file-broker"}}
    file-broker-storage-dns-domain-0: file-storage.{{ $.Values.project }}.svc.cluster.local
    {{- end }}

    {{- if eq $deployment.name "toolbox"}}
    {{- if $.Values.toolsBin.version }}
    toolbox-runtime-tools-bin-name: {{ $.Values.toolsBin.version }}
    {{- end }}
    {{- end }}
      
    {{- if eq $deployment.name "scheduler"}}
    scheduler-bash-script-dir-in-jar: "bash-job-scheduler/openshift"
    scheduler-bash-image-repository: {{ $.Values.image.repository }}
    scheduler-bash-image-tag: {{ $.Values.image.tag }}
    {{- end }}

    # include custom configs in the end to override possible default values above
    {{ include "chipster.listDeploymentConfigs" $deployment | indent 4 }}
{{- end }}
{{- end }}
{{- end }}