# Chipster service-locator configuration
# service-locator has its own template, because the addresses of all other
# services are needed only here
apiVersion: v1
kind: Secret
metadata:
  name: service-locator
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    # keep comments of individual services outside of range, otherwise those are repeated in generated secret
    # file-broker finds file-storage(s) from DNS
    # file-storage doesn't have admin API
    {{- range $deploymentKey, $deployment := .Values.deployments }}
    {{- if ne $deployment.name "file-storage" }}
    url-int-{{ $deployment.name }}: http://{{ $deployment.name }}
    url-admin-ext-{{ $deployment.name }}: https://{{ $deployment.name }}-admin-{{ $.Values.project }}.{{ $.Values.domain }}
    url-admin-int-{{ $deployment.name }}: http://{{ $deployment.name }}-admin
    {{- if ne $deployment.name "web-server" }}
    url-ext-{{ $deployment.name }}: https://{{ $deployment.name }}-{{ $.Values.project }}.{{ $.Values.domain }}
    {{- end }}
    {{- end }}
    {{- end }}

    # websockets
    url-int-session-db-events: ws://session-db-events
    url-ext-session-db-events: wss://session-db-events-{{ $.Values.project }}.{{ $.Values.domain }}

    # delete file-storage from service-locator, because it's found from DNS
    url-int-file-storage: ""
    url-admin-int-file-storage: ""

    # use the root path for the  web-server
    url-ext-web-server: https://{{ $.Values.project }}.{{ $.Values.domain }}

    service-password-service-locator: {{ $.Values.deployments.serviceLocator.password | quote }}

    # include custom configs in the end to override possible default values above
    {{ include "chipster.listDeploymentConfigs" $.Values.deployments.serviceLocator | indent 4 }}
