---
apiVersion: v1
kind: Secret
metadata:
  name: web-server-app
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    {{- include "chipster.listDeploymentConfigs" $.Values.app | indent 4 }}
