---

apiVersion: v1
kind: Secret
metadata:
  name: web-server-app
  labels:
    app: chipster
type: Opaque
chipsterConfig:
  service-locator: https://service-locator-{{ $.Values.project }}.{{ $.Values.domain }}
  # otherwise this is a copy from https://github.com/chipster/chipster-web/blob/master/src/assets/conf/chipster.yaml. 
  # TODO Change app to use defaults automatically to avoid this copy like in backend

  terms-of-use-auths: ["haka"]
  terms-of-use-path: assets/html/terms-of-use-v1.html
  terms-of-use-version: 2
  # service-locator: http://localhost:8003
  #service-locator: https://service-locator-chipster.rahti-int-app.csc.fi

  home-path: assets/html/app-home.html
  home-header-path: assets/html/app-home-header.html
  accessibility-path: assets/html/accessibility.html
  contact-path: assets/html/app-contact.html
  access-path: assets/html/access.html
  privacy-notice-path: assets/html/privacy-notice.html

  # Bio modules and manual
  modules: ["NGS", "Microarray", "Misc"]
  manual-path: assets/manual/
  manual-tool-postfix: .html
  app-name: Chipster
  app-id: chipster

  example-session-owner-user-id: jaas/example_session_owner
  support-session-owner-user-id: jaas/support_session_owner

  jaas-description: ""

  visualization-blacklist: []
