---
apiVersion: v1
kind: Secret
metadata:
  name: web-server-app
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    # when there are duplicate keys, the first seems to win in the yaml parser in the web app (opposite of what happens in the backend)
    # include custom configs first to be able to override the service locator below
    {{- include "chipster.listDeploymentConfigs" $.Values.app | indent 4 }}

    service-locator: https://service-locator-{{ $.Values.project }}.{{ $.Values.domain }}
