- name: Add the Helm repo of cert-manager
  shell: helm repo add jetstack https://charts.jetstack.io

- name: Update Helm repo
  shell: helm repo update

- name: Install CustomResourceDefinitions
  shell: kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.15.1/cert-manager.crds.yaml

- name: Create a namespace for cert-manager
  shell: kubectl create namespace cert-manager | true
