apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: comp-mylly
  name: comp-mylly
spec:
  output:
    to:
      kind: ImageStreamTag
      name: comp-mylly:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM chipster-web-server

      RUN apt-get update -y \ 
        && apt-get install -y python-pip python3-setuptools python3-dev \
        && apt-get clean \
        && easy_install3 pip

      # what is using this .cache?
      RUN mkdir -p /home/user/.cache \
        && chown $(whoami) /home/user/.cache \
        && mkdir -p /homeappl \
        && ln -s /appl /homeappl/appl_taito
        
      RUN curl -s https://korp.csc.fi/download/.mylly/kielipankki_local_root_install.sh | sed 's/pip /pip2 /g' | bash

      CMD ["java", "-cp", "lib/*:", "-Xmx512m", "fi.csc.chipster.comp.RestCompServer"]
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: chipster-web-server:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange:
    type: ImageChange
