apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: comp-mylly
  name: comp-mylly
spec:
  output:
    to:
      kind: ImageStreamTag
      name: comp-mylly:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM comp-16.04

      RUN apt-get update -y \ 
        && apt-get install -y python-pip python3-setuptools python3-dev python3-pip \
        && apt-get clean

      # what is using this .cache?
      RUN mkdir -p /home/user/.cache \
        && chown $(whoami) /home/user/.cache \
        && mkdir -p /homeappl \
        && ln -s /appl /homeappl/appl_taito
      
      # don't update pip and setuptools
      # these old versions from apt are compatible with the old python 3.5
      RUN curl -s https://korp.csc.fi/download/.mylly/kielipankki_local_root_install.sh \
      | grep -v 'pip2' \
      | grep -v 'pip3 install -U pip' \
      | grep -v 'pip3 install -U setuptools' \
      | bash

      CMD ["java", "-cp", "lib/*:", "-Xmx512m", "fi.csc.chipster.comp.RestCompServer"]
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: comp-16.04:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange:
    type: ImageChange
