bases:
  - ../builds
resources:
  - comp-16-04-mylly-bc.yaml
  - comp-16-04-mylly-is.yaml
  - mylly-tools-bc.yaml
  - mylly-tools-is.yaml
  - web-server-mylly-bc.yaml
  - web-server-mylly-is.yaml
patchesJson6902:
  - target:
      group: build.openshift.io
      version: v1
      kind: BuildConfig
      name: toolbox
    path: bc-toolbox-mylly.yaml
