apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: chipster-tools
  name: chipster-tools
spec:
  output:
    to:
      kind: ImageStreamTag
      name: chipster-tools:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: ""
    git:
      ref: master
      uri: https://github.com/chipster/chipster-tools.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: base-24-04:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
    - imageChange:
      type: ImageChange
