apiVersion: v1
kind: Template
metadata:
  name: ${NAME}
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      build: web-server-mylly
    name: web-server-mylly
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: web-server-mylly:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      dockerfile: ""
      type: Dockerfile
      images:
      - as: null
        from:
          kind: ImageStreamTag
          name: chipster-web:latest
        paths:
        - destinationDir: chipster-web
          sourcePath: /home/user/chipster-web
      - as: null
        from:
          kind: ImageStreamTag
          name: mylly-tools:latest
        paths:
        - destinationDir: mylly-tools-manual
          sourcePath: /home/user/mylly-tools/manual
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: chipster-web-server:latest
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: ${GITHUB_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange:
      type: ImageChange
    - imageChange:
        from:
          kind: ImageStreamTag
          name: chipster-web:latest
      type: ImageChange
    - imageChange:
        from:
          kind: ImageStreamTag
          name: mylly-tools:latest
      type: ImageChange
parameters:
  - name: NAME
  - name: BRANCH
  - name: GITHUB_SECRET
  - name: GENERIC_SECRET