apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: base-java-16.04
  name: base-java-16.04
spec:
  output:
    to:
      kind: ImageStreamTag
      name: base-java-16.04:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: ""
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: base-16.04:latest
    type: Docker
  triggers:
  - type: ConfigChange
  - imageChange:
    type: ImageChange
