---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: backup
spec:
  replicas: 0

---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: job-history
spec:
  replicas: 0
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: influxdb
spec:
  replicas: 0
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: grafana
spec:
  replicas: 0
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: logstash
spec:
  replicas: 0
# ---
# apiVersion: apps.openshift.io/v1
# kind: DeploymentConfig
# metadata:
#   name: replay
# spec:
#   replicas: 0
