apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: chipster-web-server-java
  name: chipster-web-server-java
spec:
  output:
    to:
      kind: ImageStreamTag
      name: chipster-web-server-java:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: ""
    images:
      - as: null
        from:
          kind: ImageStreamTag
          name: chipster-web-server-build:latest
        paths:
          - destinationDir: chipster-web-server-build
            sourcePath: /opt/chipster
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: base-java-utils:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: chipster-web-server-build:latest
      type: ImageChange
    - type: ConfigChange
    - imageChange:
      type: ImageChange
