{{ if eq $.Values.tls.env "prod" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chipster-tls
  namespace: default
spec:
  secretName: chipster-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ $.Values.host }}
  dnsNames:
  - {{ $.Values.host }}
{{ end }}
