apiVersion: v1
kind: Template
metadata:
  name: ${NAME}
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      build: ${NAME}
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
parameters:
  - name: NAME
