apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ubuntu
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      build: base
    name: ubuntu
  spec:
    lookupPolicy:
      local: false
    tags:
      - from:
          kind: DockerImage
          name: 'ubuntu:16.04'
        name: '16.04'
