apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: base-java-comp
  name: base-java-comp
spec:
  output:
    to:
      kind: ImageStreamTag
      name: base-java-comp:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: ""
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: base-java-16-04:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange:
    type: ImageChange
