FROM base-java

RUN apt-get update -y \ 
&& apt-get install -y \  
#fastx-toolkit \
#python-numpy \
#python-zsi \
#libgfortran3 \
#libpng12-0 \
#libreadline6 \
ghostscript \
python3-pip \
python3-matplotlib \
cython \
libgd-dev \
python3-yaml \
libcurl4 \
libglib2.0-0 \
libglu1-mesa \
libxml2 \
mesa-common-dev \
tcl \
tk \
xorg-dev \
unixodbc \
gawk \
build-essential \
gfortran \
libcurl4-openssl-dev \
libglib2.0-dev \
libglu1-mesa-dev \
libgsl0-dev \
libpng-dev \
libreadline-dev \
libxml2-dev \
mesa-common-dev \
tcl-dev \
tk-dev \
xorg-dev \
python-dev \
unixodbc-dev \
libnetcdf-dev \
libjson-perl \
libcairo-perl \
libtext-simpletable-perl \
libcontextual-return-perl \
libwant-perl \
libhttp-parser-perl \
cpanminus \
pbzip2 \
xfsprogs \
#libssl-dev for compiling python
libssl-dev \
#libbz2-dev for R-3.3+
libbz2-dev \
# libnlopt0 for Seurat
libnlopt0 \
#libnlopt-dev for Seurat
libnlopt-dev \
#liblzo2-devor rseqc 
#liblzo2-dev \
#libnetcdf11 \ 
#libgsl0ldbl \
#libnetcdf6 \
#libgsl-dev \ 
&& apt-get clean
