{{- range $deploymentKey, $deployment := .Values.deployments }}
{{- if and $deployment.adminPort (ne $deployment.name "file-storage") }}
# Kubernetes service for the main admin port of each Chipster service,
# making the port accessible for other services
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $deployment.name }}-admin
  labels:
    app: chipster
spec:
  ports:
      # the service can be accessed with the default port
    - port: 80
      # use the named port of the deployment
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    app: chipster
    deployment: {{ $deployment.name }}
{{- end }}
{{- end }}