{{- range $deploymentKey, $deployment := .Values.deployments }}
{{- if ne $deployment.name "file-storage" }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $deployment.name }}-admin
  labels:
    app: chipster
  annotations:
    "traefik.frontend.rule.type": PathPrefixStrip
spec:
# from chart template, not tested
{{- if $.Values.ingress.tls }}
  tls:
  {{- range $.Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - http:
        paths:
          # other services are served in subpaths
          - path: /{{ $deployment.name }}-admin 
            backend:
              serviceName: {{ $deployment.name }}-admin
              # services map everything to the port 80
              servicePort: 80
{{- end }}
{{- end }}
