---
# Chipster auth configuration
# auth has its own template, because it needs the service passwords of all other services
apiVersion: v1
kind: Secret
metadata:
  name: auth
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    url-int-service-locator: http://service-locator

    # service passwords of all other Chipster services
    {{- range $deploymentKey, $deployment := .Values.deployments }}
    {{- if ne $deployment.name "single-shot-comp"}}
    service-password-{{ $deployment.name }}: {{ (required "deployments.*.password is required" $deployment.password) | quote }}
    {{- end }}
    {{- end }}

    auth-monitoring-password: {{ (required "serviceAccounts.monitoring.password is required" .Values.serviceAccounts.monitoring.password) | quote }}
    
    # TODO why jdbc requires .default.svc.cluster.local when we are in the same namespace and psql works without it?
    # postgresql service name is RELEASE_NAME-ALIAS
    db-url-auth: "jdbc:postgresql://chipster-auth-postgresql.default.svc.cluster.local:5432/auth_db"
    # the postgresql alias has to be accessed with a "index" function, because it contains a dash character
    db-pass-auth: {{ (required "auth-postgresql.postgresqlPassword is requied" (index $.Values "auth-postgresql").postgresqlPassword) | quote }}
    db-user: postgres
    # disable H2
    db-fallback: false
    jws-private-key-auth: {{ (required "tokens.auth.privateKey is required" $.Values.tokens.auth.privateKey) | quote }}

    # Chipster configs
    {{ include "chipster.listDeploymentConfigs" .Values.deployments.auth | indent 4 }}
  {{ include "chipster.listDeploymentConfigFiles" .Values.deployments.auth | indent 2 }}
