---
apiVersion: v1
kind: Secret
metadata:
  name: auth
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    url-int-service-locator: http://service-locator
    {{- range $deploymentKey, $deployment := .Values.deployments }}
    service-password-{{ $deployment.name }}: {{ (required "deployments.*.password is required" $deployment.password) | quote }}
    {{- end }}
    # TODO why jdbc requires .default.svc.cluster.local when we are in the same namespace and psql works without it?
    db-url-auth: "jdbc:postgresql://chipster-auth-postgresql.default.svc.cluster.local:5432/auth_db"
    db-pass-auth: {{ (required "auth-postgresql.postgresqlPassword is requied" (index $.Values "auth-postgresql").postgresqlPassword) | quote }}
    db-user: postgres
    jws-private-key-auth: {{ (required "tokens.auth.privateKey is required" $.Values.tokens.auth.privateKey) | quote }}

    {{- range $configKey, $value := .Values.deployments.auth.configs }}
    {{ $configKey }}: {{ $value }}
    {{- end }}
