{{- range $index, $deployment := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deployment.name }}
  labels:
    app: chipster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chipster
      deployment: {{ $deployment.name }}
  template:
    metadata:
      labels:
        app: chipster
        deployment: {{ $deployment.name }}
    spec:
      containers:
        - name: {{ $.Chart.Name }}-{{ $deployment.name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}            
          env:
            - name: JAVA_CLASS
              value: {{ $deployment.class }}
          image: {{ $deployment.image }}
          imagePullPolicy: {{ $.Values.image.localPullPolicy }}
          ports:
            {{- if $deployment.apiPort }}
            - name: api
              containerPort: {{ $deployment.apiPort }}
              protocol: TCP
            {{- end }}
            {{- if $deployment.adminPort }}
            - name: admin
              containerPort: {{ $deployment.adminPort }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /admin/alive
              port: admin
          # dead lock between auth and service-locator
          # readinessProbe:
          #   httpGet:
          #     path: /admin/alive
          #     port: admin
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
            - name: conf
              mountPath: "/opt/chipster/conf"
              readOnly: true
      volumes:
        - name: conf
          secret:
            secretName: {{ $deployment.name }}
{{- end }}
