# deployment for each Chipster service
{{- range $deploymentKey, $deployment := .Values.deployments }}
{{- if ne $deployment.name "file-storage" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deployment.name }}
  labels:
    app: chipster
spec:
  {{- if $deployment.replicas }}
  replicas: {{ $deployment.replicas }}
  {{- else }}
  replicas: {{ $.Values.deploymentDefault.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: chipster
      deployment: {{ $deployment.name }}
  template:
    metadata:
      labels:
        app: chipster
        deployment: {{ $deployment.name }}
    spec:
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $deployment.name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}            
          # Java class to start for the chipster-web-server image
          env:
            - name: JAVA_CLASS
              value: {{ $deployment.class }}
          {{- if $deployment.useDefaultImageRepo }}
          image: {{$.Values.image.chipsterImageRepo}}{{ $deployment.image }}
          {{- else }}
          image: {{ $deployment.image }}
          {{- end }}
          # pull policy for Chipster images
          imagePullPolicy: {{ $.Values.image.localPullPolicy }}
          ports:
            {{- if $deployment.apiPort }}
            - name: api
              containerPort: {{ $deployment.apiPort }}
              protocol: TCP
            {{- end }}
            {{- if $deployment.adminPort }}
            - name: admin
              containerPort: {{ $deployment.adminPort }}
              protocol: TCP
            {{- end }}
            {{- if $deployment.eventsPort }}
            - name: events
              containerPort: {{ $deployment.eventsPort }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /admin/alive
              port: admin
            initialDelaySeconds: 30
          # dead lock between auth and service-locator
          # readinessProbe:
          #   httpGet:
          #     path: /admin/alive
          #     port: admin
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
            # config secret is mounted to all services          
            - name: conf
              mountPath: {{ $deployment.workDir }}/conf
              readOnly: true
            # auth's users file
            {{- if eq $deployment.name "auth" }}
            - name: security
              mountPath: {{ $deployment.workDir }}/security
              readOnly: true
            {{- end }}
            # web-server's web app config
            {{- if eq $deployment.name "web-server" }}
            - name: app-conf
              mountPath: {{ $deployment.workDir }}/web-root/assets/conf
              readOnly: true
            {{- end }}
            # tools-bin for toolbox and comp
            {{- if and (or $.Values.toolsBin.version $.Values.toolsBin.hostPath) (or (eq $deployment.name "comp") (eq $deployment.name "toolbox")) }}
            - name: tools-bin
              mountPath: /mnt/tools
              readOnly: {{ $.Values.toolsBin.readOnly }}
            {{- end }}
            {{- if and $.Values.tools.hostPath (eq $deployment.name "toolbox") }}
            - name: tool-scripts
              mountPath: /opt/chipster/toolbox/tools
            {{- end }}
            {{- if and $.Values.tools.manualHostPath (eq $deployment.name "web-server") }}
            - name: tool-manuals
              mountPath: /opt/chipster/web-root/assets/manual
            {{- end }}
            {{- if and $.Values.html.hostPath (eq $deployment.name "web-server") }}
            - name: html
              mountPath: /opt/chipster/web-root/assets/html
            {{- end }}
            {{- if eq $deployment.name "comp" }}
            - name: jobs-data
              mountPath: {{ $deployment.workDir }}/jobs-data
            {{- end }}
            {{- if eq $deployment.name "backup" }}
            - name: db-backups
              mountPath: {{ $deployment.workDir }}/db-backups            
            - name: home-gnupg
              mountPath: /home/user/.gnupg
            {{- end }}
      volumes:
        - name: conf
          secret:
            secretName: {{ $deployment.name }}
        {{- if eq $deployment.name "auth" }}
        - name: security
          secret:
            secretName: auth-security
        {{- end}}
        {{- if eq $deployment.name "web-server" }}
        - name: app-conf
          secret:
            secretName: web-server-app
        {{- end}}
        {{- if and (or $.Values.toolsBin.version $.Values.toolsBin.hostPath) (or (eq $deployment.name "comp") (eq $deployment.name "toolbox")) }}
        - name: tools-bin
        {{- if $.Values.toolsBin.hostPath }}
          hostPath:
            path: {{ $.Values.toolsBin.hostPath }}
            type: Directory
        {{- else }}
          persistentVolumeClaim:
            claimName: tools-bin-{{ $.Values.toolsBin.version }}
        {{- end}}
        {{- end}}
        {{- if and $.Values.tools.hostPath (eq $deployment.name "toolbox") }}
        - name: tool-scripts
          hostPath:
            # directory location on host
            path: {{ $.Values.tools.hostPath }}
            type: Directory
        {{- end}}
        {{- if and $.Values.tools.manualHostPath (eq $deployment.name "web-server") }}
        - name: tool-manuals
          hostPath:
            # directory location on host
            path: {{ $.Values.tools.manualHostPath }}
            type: Directory
        {{- end}}
        {{- if and $.Values.html.hostPath (eq $deployment.name "web-server") }}
        - name: html
          hostPath:
            # directory location on host
            path: {{ $.Values.html.hostPath }}
            type: Directory
        {{- end}}
        {{- if eq $deployment.name "comp" }}
        - name: jobs-data
          emptyDir: {}
        {{- end}}
        {{- if eq $deployment.name "backup" }}
        - name: db-backups
          emptyDir: {}
        - name: home-gnupg
          emptyDir: {}
        {{- end}}
{{- end }}
{{- end }}
