# file-broker's storage for users' files
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: chipster
  name: file-broker-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.deployments.fileBroker.storageVolumeSize }}
