{{- range $index, $deployment := .Values.deployments }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $deployment.name }}
  labels:
    app: chipster
  annotations:
    "traefik.frontend.rule.type": PathPrefixStrip
spec:
{{- if $.Values.ingress.tls }}
  tls:
  {{- range $.Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - http:
        paths:
          - path: /{{ $deployment.name }}
            backend:
              serviceName: {{ $deployment.name }}
              servicePort: 80
{{- end }}
