{{- range $deploymentKey, $deployment := .Values.deployments }}
{{- if ne $deployment.name "file-storage" }}
# http/websocket reverse proxy for making Chipster APIs accessible
# from the internet
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $deployment.name }}
  labels:
    app: chipster
  annotations:
    "traefik.frontend.rule.type": PathPrefixStrip
    {{- if $.Values.tls.env }}
    "traefik.ingress.kubernetes.io/redirect-entry-point": https
    {{- end }}
spec:
  tls:
  # tls with Chipster Let's Encrypt templates
  {{- if eq $.Values.tls.env "prod" }}
    - secretName: chipster-tls
  {{- end }}  
  {{- if eq $.Values.tls.env "staging" }}
    # this won't really work, APIs don't trust the staging certificates (TODO those should ue only internal addresses)
    - secretName: chipster-tls-staging
  {{- end }}
  # the default Helm TLS config from nginx-test
  {{- range $.Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  rules:
    - http:
        paths:
          {{- if eq $deployment.name "web-server" }}
          # serve web app in the root
          - path: /
          {{- else }}
          # other services are served in subpaths
          - path: /{{ $deployment.name }}
          {{- end }}
            backend:
              serviceName: {{ $deployment.name }}
              # services map everything to the port 80
              servicePort: 80
{{- end }}
{{- end }}
