{{- if eq .Values.ingress.kind "Ingress" }}
---
# http/websocket reverse proxy for making Chipster APIs accessible
# from the internet
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chipster
  labels:
    app: chipster
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - http:
      paths:
      {{- range $deploymentKey, $deployment := .Values.deployments }}
      {{- if ne $deployment.name "file-storage" }}
      {{- if ne $deployment.name "single-shot-comp" }}
      {{- if eq $deployment.name "web-server" }}
      - path: /(.*)
      {{ else }}
      - path: /{{ $deployment.name }}/(.*)
      {{- end }}
        pathType: Prefix
        backend:
          service:
            name: {{ $deployment.name }}
            port: 
              number: 80
      # create admin route
      # if enabled for this deployment or using default config and it's enabled
      {{- if or (eq $deployment.adminRoute "enable") (and (eq $deployment.adminRoute "default") (eq $.Values.deploymentDefault.adminRoute "enable")) }}
      - path: /{{ $deployment.name }}-admin/(.*)
        pathType: Prefix
        backend:
          service:            
            name: {{ $deployment.name }}-admin
            port: 
              number: 80
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      - path: /session-db-events(.*)
        pathType: Prefix
        backend:
          service:
            name: session-db-events
            port: 
              number: 80
{{- end }}