apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: chipster
  name: tools-bin-{{ $.Values.toolsBin.version }}-temp
spec:
  accessModes:
    # - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.toolsBin.volumeSize }}