# k3s local-path doesn't support ReadWriteMany
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: chipster
  name: tools-bin-{{ $.Values.toolsBin.version }}
spec:
  accessModes:
    # - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.toolsBin.volumeSize }}

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     app: chipster
#   name: tools-bin-{{ $.Values.toolsBin.version }}
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: {{ $.Values.toolsBin.volumeSize }}

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   labels:
#     app: chipster
#   name: tools-bin-{{ $.Values.toolsBin.version }}
# spec:
#   capacity:
#     storage: {{ $.Values.toolsBin.volumeSize }}
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteMany
#   storageClassName: manual
#   hostPath:
#     path: /mnt/data/tools-bin-{{ $.Values.toolsBin.version }}
