apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bash-job-scheduler-rb
  #
  # The namespace of the RoleBinding determines where the permissions are granted.
  # This only grants permissions within the "default" namespace.
  namespace: default
subjects:
- kind: ServiceAccount
  name: bash-job-scheduler
  # service account's namespace
  namespace: default
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
