apiVersion: v1
kind: Secret
metadata:
  name: auth-security
  labels:
    app: chipster
type: Opaque
stringData:
  users: |-
    # User accounts
    #
    # One user per line, format as follows:
    #
    # username:password:expiration date (yyyy-mm-dd):comment
    #
    {{- range $key, $user := .Values.users }}
    {{ $key }}:{{ $user.password }}::
    {{- end }}
    