{{- range $index, $deployment := .Values.deployments }}
{{- if and (ne $deployment.name "service-locator") (ne $deployment.name "auth") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $deployment.name }}
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    url-int-service-locator: http://service-locator
    service-password-{{ $deployment.name }}: abc
    {{- if eq $deployment.name "session-db"}}
    db-url-session-db: "jdbc:postgresql://session-db-postgresql.default.svc.cluster.local:5432/session_db_db"
    db-pass-session-db: {{ $.Values.passwords.sessionDbPostgresql }}
    db-user: postgres
    {{- end }}
    {{- if eq $deployment.name "job-history"}}
    db-url-job-history: "jdbc:postgresql://job-history-postgresql.default.svc.cluster.local:5432/job_history_db"
    db-pass-job-history: {{ $.Values.passwords.jobHistoryPostgresql }}
    db-user: postgres
    {{- end }}
{{- end }}
{{- end }}