---
apiVersion: v1
kind: Secret
metadata:
  name: auth
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    url-int-service-locator: http://service-locator
    {{- range $index, $deployment := .Values.deployments }}
    service-password-{{ $deployment.name }}: abc
    {{- end }}
