{{- range $deploymentKey, $deployment := .Values.deployments }}
{{- if and (ne $deployment.name "service-locator") (ne $deployment.name "auth") }}
# Chipster configuration file for most of the Chipster services
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $deployment.name }}
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    url-int-service-locator: http://service-locator
    service-password-{{ $deployment.name }}: {{ $deployment.password | quote }}
    {{- if eq $deployment.name "session-db"}}
    db-url-session-db: "jdbc:postgresql://chipster-session-db-postgresql.default.svc.cluster.local:5432/session_db_db"
    db-pass-session-db: {{ (required "session-db-postgresql.postgresqlPassword is requied" (index $.Values "session-db-postgresql").postgresqlPassword) | quote }}
    db-user: postgres
    {{- end }}
    {{- if eq $deployment.name "job-history"}}
    db-url-job-history: "jdbc:postgresql://chipster-job-history-postgresql.default.svc.cluster.local:5432/job_history_db"
    db-pass-job-history: {{ (required "job-history-postgresql.postgresqlPassword is required" (index $.Values "job-history-postgresql").postgresqlPassword) | quote }}
    db-user: postgres
    {{- end }}
    {{- if eq $deployment.name "session-db"}}
    jws-private-key-session-db: {{ (required "tokens.sessionDb.privateKey is required" $.Values.tokens.sessionDb.privateKey) | quote }}
    {{- end }}

    {{ include "chipster.listDeploymentConfigs" $deployment | indent 4 }}
{{- end }}
{{- end }}