---
apiVersion: v1
kind: Secret
metadata:
  name: auth
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    url-int-service-locator: http://service-locator
    {{- range $deploymentKey, $deployment := .Values.deployments }}
    service-password-{{ $deployment.name }}: {{ $deployment.password | quote }}
    {{- end }}
    # TODO why jdbc requires .default.svc.cluster.local when we are in the same namespace and psql works without it?
    db-url-auth: "jdbc:postgresql://auth-postgresql.default.svc.cluster.local:5432/auth_db"
    db-pass-auth: {{ $.Values.databases.auth.password }}
    db-user: postgres
    jws-private-key-auth: {{ $.Values.tokens.auth.privateKey | quote }}
