---
apiVersion: v1
kind: Secret
metadata:
  name: auth
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    url-int-service-locator: http://service-locator
    {{- range $index, $deployment := .Values.deployments }}
    service-password-{{ $deployment.name }}: abc
    {{- end }}
    # TODO why jdbc requires .default.svc.cluster.local when we are in the same namespace and psql works without it?
    db-url-auth: "jdbc:postgresql://auth-postgresql.default.svc.cluster.local:5432/auth_db"
    db-pass-auth: {{ $.Values.passwords.authPostgresql }}
    db-user: postgres
