{{- range $deploymentKey, $deployment := .Values.deployments }}
{{- if ne $deployment.name "service-locator" }}
{{- if ne $deployment.name "auth" }}
# Chipster configuration file for most of the Chipster services
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $deployment.name }}
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    url-int-service-locator: http://service-locator
    {{- if ne $deployment.name "single-shot-comp" }}
    service-password-{{ $deployment.name }}: {{ $deployment.password | quote }}
    {{- if or (eq $deployment.name "session-db") (eq $deployment.name "backup")}}
    db-url-session-db: "jdbc:postgresql://chipster-session-db-postgresql.default.svc.cluster.local:5432/session_db_db"
    db-pass-session-db: {{ (required "session-db-postgresql.postgresqlPassword is requied" (index $.Values "session-db-postgresql").postgresqlPassword) | quote }}
    db-user: postgres
    db-fallback: false
    {{- end }}
    {{- if eq $deployment.name "session-db"}}
    jws-private-key-session-db: {{ (required "tokens.sessionDb.privateKey is required" $.Values.tokens.sessionDb.privateKey) | quote }}
    {{- end }}
    {{- if or (eq $deployment.name "job-history") (eq $deployment.name "backup")}}
    db-url-job-history: "jdbc:postgresql://chipster-job-history-postgresql.default.svc.cluster.local:5432/job_history_db"
    db-pass-job-history: {{ (required "job-history-postgresql.postgresqlPassword is required" (index $.Values "job-history-postgresql").postgresqlPassword) | quote }}
    db-user: postgres
    db-fallback: false
    {{- end }}

    {{- if eq $deployment.name "backup"}}
    db-url-auth: "jdbc:postgresql://chipster-auth-postgresql.default.svc.cluster.local:5432/auth_db"
    # the postgresql alias has to be accessed with a "index" function, because it contains a dash character
    db-pass-auth: {{ (required "auth-postgresql.postgresqlPassword is requied" (index $.Values "auth-postgresql").postgresqlPassword) | quote }}
    db-user: postgres
    # disable H2
    db-fallback: false
    {{- end }}
    
    {{- if eq $deployment.name "file-broker"}}
    file-broker-storage-dns-domain-0: file-storage.default.svc.cluster.local
    {{- end }}

    {{- if eq $deployment.name "scheduler"}}
    service-password-single-shot-comp: {{ $.Values.deployments.singleShotComp.password | quote }}
    scheduler-bash-run-script-stdin-file: "conf/bash-job-scheduler-run-stdin.yaml"
    {{- end }}
    {{- end }}
    
    {{ include "chipster.listDeploymentConfigs" $deployment | indent 4 }}
  {{- if eq $deployment.name "scheduler"}}
  bash-job-scheduler-run-stdin.yaml: |
    # example template for development
    apiVersion: v1
    kind: Pod
    metadata:
      name: ""
      labels:
        comp-job: ""
    spec:
      containers:
      - name: comp-job
        image: ""
        imagePullPolicy: IfNotPresent
        command: ["java",  "-cp", "lib/*:", "fi.csc.chipster.comp.SingleShotComp"]
        resources:
          limits:
            cpu: ""
            memory: ""
          requests:
            cpu: ""
            memory: ""
        volumeMounts:
        - mountPath: /opt/chipster/conf
          name: conf
          readOnly: true
        - mountPath: /opt/chipster/jobs-data
          name: jobs-data
        {{- if or $.Values.toolsBin.version $.Values.toolsBin.hostPath }}
        - mountPath: /opt/chipster/tools
          name: tools-bin
          readOnly: true
        {{- end }}
      volumes:
      - name: conf
        secret:
          defaultMode: 420
          secretName: single-shot-comp
      - emptyDir: {}
        name: jobs-data  
      {{- if or $.Values.toolsBin.version $.Values.toolsBin.hostPath }}
      - name: tools-bin
      {{- if $.Values.toolsBin.hostPath }}
        hostPath:
          path: {{ $.Values.toolsBin.hostPath }}
          type: Directory
      {{- else }}
        persistentVolumeClaim:
          claimName: tools-bin-{{ $.Values.toolsBin.version }}
      {{- end }}
      {{- end }}
      restartPolicy: Never
    {{- end }}
  {{ include "chipster.listDeploymentConfigFiles" $deployment | indent 2 }}
{{- end }}
{{- end }}
{{- end }}