{{- range $index, $deployment := .Values.deployments }}
{{- if ne $deployment.name "service-locator" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $deployment.name }}
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    url-int-service-locator: http://service-locator
{{- end }}
{{- end }}