{{- range $deploymentKey, $deployment := .Values.deployments }}
{{- if ne $deployment.name "service-locator" }}
{{- if ne $deployment.name "auth" }}
# Chipster configuration file for most of the Chipster services
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $deployment.name }}
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    url-int-service-locator: http://service-locator
    {{- if ne $deployment.name "single-shot-comp" }}
    service-password-{{ $deployment.name }}: {{ $deployment.password | quote }}
    {{- if or (eq $deployment.name "session-db") (eq $deployment.name "backup")}}
    db-url-session-db: "jdbc:postgresql://chipster-session-db-postgresql.default.svc.cluster.local:5432/session_db_db"
    db-pass-session-db: {{ (required "session-db-postgresql.auth.postgrePassword is requied" (index $.Values "session-db-postgresql").auth.postgresPassword) | quote }}
    db-user: postgres
    db-fallback: false
    {{- end }}
    {{- if or (eq $deployment.name "job-history") (eq $deployment.name "backup")}}
    db-url-job-history: "jdbc:postgresql://chipster-job-history-postgresql.default.svc.cluster.local:5432/job_history_db"
    db-pass-job-history: {{ (required "job-history-postgresql.auth.postgresPassword is required" (index $.Values "job-history-postgresql").auth.postgresPassword) | quote }}
    db-user: postgres
    db-fallback: false
    {{- end }}

    {{- if eq $deployment.name "backup"}}
    db-url-auth: "jdbc:postgresql://chipster-auth-postgresql.default.svc.cluster.local:5432/auth_db"
    # the postgresql alias has to be accessed with a "index" function, because it contains a dash character
    db-pass-auth: {{ (required "auth-postgresql.auth.postgresPassword is requied" (index $.Values "auth-postgresql").auth.postgresPassword) | quote }}
    db-user: postgres
    # disable H2
    db-fallback: false
    {{- end }}
    
    {{- if eq $deployment.name "file-broker"}}
    file-broker-storage-dns-domain-0: file-storage.default.svc.cluster.local
    {{- end }}

    {{- if eq $deployment.name "toolbox"}}
    {{- if $.Values.toolsBin.version }}
    toolbox-runtime-tools-bin-name: {{ $.Values.toolsBin.version }}
    {{- end }}
    {{- end }}
     
    {{- if eq $deployment.name "scheduler"}}
    scheduler-bash-storage-class: local-path
    scheduler-bash-script-dir-in-jar: "bash-job-scheduler/k3s"
    scheduler-bash-image-repository: {{ $.Values.image.chipsterImageRepo }}
    scheduler-bash-image-tag: {{ $.Values.image.tag }}
    scheduler-bash-pod-anti-affinity: false
    {{- if $.Values.toolsBin.hostPath }}
    scheduler-bash-tools-bin-host-mount-path: {{ $.Values.toolsBin.hostPath }}
    {{- end }}
    {{- end }}
    {{- end }}
    # include custom congigs in the end to override possible default values above
    {{ include "chipster.listDeploymentConfigs" $deployment | indent 4 }}
  {{ include "chipster.listDeploymentConfigFiles" $deployment | indent 2 }}
{{- end }}
{{- end }}
{{- end }}