apiVersion: v1
kind: Service
metadata:
  name: {{ include "chipster.fullname" . }}-auth-api
  labels:
    app: chipster
spec:
  ports:
    - port: 80
      targetPort: api
      protocol: TCP
      name: api
  selector:
    app: chipster
