apiVersion: v1
kind: Secret
metadata:
  name: service-locator
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    {{- range $deploymentKey, $deployment := .Values.deployments }}
    # scheduler doesn't have Rest API
    {{- if ne $deployment.name "scheduler"}}
    url-int-{{ $deployment.name }}: http://{{ $deployment.name }}
    url-admin-ext-{{ $deployment.name }}: http://{{ $.Values.host }}/{{ $deployment.name }}-admin
    {{- end }}
    {{- if ne $deployment.name "web-server"}}
    url-ext-{{ $deployment.name }}: http://{{ $.Values.host }}/{{ $deployment.name }}
    {{- end }}
    {{- end }}

    # websockets
    url-int-scheduler: ws://scheduler
    url-int-session-db-events: ws://session-db-events
    url-ext-session-db-events: ws://{{ $.Values.host }}/session-db-events

    # use the root path for the  web-server
    url-ext-web-server: http://{{ required "host (IP or DNS name) is required" $.Values.host }}

    service-password-service-locator: {{ $.Values.deployments.serviceLocator.password | quote }}
