{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chipster.serviceAccountName" . }}
  labels:
{{ include "chipster.labels" . | nindent 4 }}
{{- end -}}
