# Chipster service-locator configuration
# service-locator has its own template, because the addresses of all other
# services are needed only here
apiVersion: v1
kind: Secret
metadata:
  name: service-locator
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    # keep comments of individual services outside of range, otherwise those are repeated in generated secret
    # scheduler doesn't have Rest API
    # file-broker finds file-storage(s) from DNS
    {{- range $deploymentKey, $deployment := .Values.deployments }}
    {{- if and (ne $deployment.name "scheduler") (ne $deployment.name "file-storage") }}
    url-int-{{ $deployment.name }}: http://{{ $deployment.name }}
    url-admin-ext-{{ $deployment.name }}: {{ include "chipster.getHttpProtocol" $ }}://{{ $.Values.host }}/{{ $deployment.name }}-admin
    {{- end }}
    {{- if and (ne $deployment.name "web-server") (ne $deployment.name "file-storage") }}
    url-ext-{{ $deployment.name }}: {{ include "chipster.getHttpProtocol" $ }}://{{ $.Values.host }}/{{ $deployment.name }}
    {{- end }}
    {{- end }}

    # websockets
    url-int-scheduler: ws://scheduler
    url-int-session-db-events: ws://session-db-events
    url-ext-session-db-events: {{ include "chipster.getWebSocketProtocol" $ }}://{{ $.Values.host }}/session-db-events

    # delete file-storage from service-locator, because it's found from DNS
    url-int-file-storage: ""
    url-admin-ext-file-storage: ""

    # use the root path for the  web-server
    url-ext-web-server: {{ include "chipster.getHttpProtocol" $ }}://{{ required "host (IP or DNS name) is required" $.Values.host }}

    service-password-service-locator: {{ $.Values.deployments.serviceLocator.password | quote }}

    {{ include "chipster.listDeploymentConfigs" .Values.deployments.serviceLocator | indent 4 }}
