{{- range $index, $deployment := .Values.deployments }}
{{- if $deployment.apiPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $deployment.name }}
  labels:
    app: chipster
spec:
  ports:
    - port: 80
      targetPort: api
      protocol: TCP
      name: api
  selector:
    app: chipster
    deployment: {{ $deployment.name }}
{{- end }}
{{- end }}