---
apiVersion: v1
kind: Service
metadata:
  name: session-db-events
  labels:
    app: chipster
spec:
  ports:
    - port: 80
      targetPort: events
      protocol: TCP
      name: events
  selector:
    app: chipster
    deployment: session-db
 