# configuration for the Chipster app, served by the Chipster web-server service
apiVersion: v1
kind: Secret
metadata:
  name: web-server-app
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    terms-of-use-auths:
      - haka
    terms-of-use-path: assets/html/terms-of-use-v1.html
    terms-of-use-version: 2
    service-locator: {{ include "chipster.getHttpProtocol" . }}://{{ .Values.host }}/service-locator
    home-path: assets/html/app-home.html
    home-header-path: assets/html/app-home-header.html
    accessibility-path: assets/html/accessibility.html
    contact-path: assets/html/app-contact.html
    access-path: assets/html/access.html
    privacy-notice-path: assets/html/privacy-notice.html
    modules:
      - NGS
      - Microarray
      - Misc
    manual-path: assets/manual/
    manual-tool-postfix: .html
    app-name: Chipster
    app-id: chipster
    example-session-owner-user-id: jaas/example_session_owner
    support-session-owner-user-id: jaas/support_session_owner
    jaas-description: ""
    visualization-blacklist: []
