# configuration for the Chipster app, served by the Chipster web-server service
apiVersion: v1
kind: Secret
metadata:
  name: web-server-app
  labels:
    app: chipster
type: Opaque
stringData:
  chipster.yaml: |-
    terms-of-use-auths:
      - haka
    terms-of-use-path: assets/csc-terms-of-use-v1.html
    terms-of-use-version: 2
    service-locator: http://{{ .Values.host }}/service-locator
    home-path: assets/manual/app-home.html
    home-header-path: assets/manual/app-home-header.html
    contact-path: assets/manual/app-contact.html
    modules:
      - NGS
      - Microarray
      - Misc
    manual-path: assets/manual/
    manual-tool-postfix: .html
    app-name: Chipster
    app-id: chipster
    favicon: assets/manual/app-chipster-icon.png
    example-session-owner-user-id: jaas/example_session_owner
    support-session-owner-user-id: jaas/support_session_owner
    visualization-blacklist: []