apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: filebeat
  name: filebeat
spec:
  output:
    to:
      kind: ImageStreamTag
      name: filebeat:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM docker.elastic.co/beats/filebeat:7.16.2
      COPY filebeat/filebeat.yml /usr/share/filebeat/filebeat.yml
      USER root
      RUN chown -R root:root /usr/share/filebeat
      USER filebeat
      CMD filebeat
    git:
      ref: master
      uri: https://github.com/chipster/chipster-openshift.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: filebeat:7.16.2
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange:
    type: ImageChange
