apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: filebeat
  name: filebeat
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: 'docker.elastic.co/beats/filebeat:7.16.1'
      name: 7.16.1
