apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: logstash
  name: logstash
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: 'docker.elastic.co/logstash/logstash:7.16.2'
      name: 7.16.2
