apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: logstash
  name: logstash
spec:
  output:
    to:
      kind: ImageStreamTag
      name: logstash:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM docker.elastic.co/logstash/logstash:7.1.1
      COPY logstash/logstash.yml /usr/share/logstash/config/logstash.yml
      COPY logstash/logstash.conf /usr/share/logstash/pipeline/logstash.conf 
      USER root
      RUN chown logstash:root /usr/share/logstash/config/logstash.yml
      RUN chown logstash:root /usr/share/logstash/pipeline/logstash.conf 
      USER logstash
      CMD logstash
    git:
      ref: master
      uri: https://github.com/chipster/chipster-openshift.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: logstash:7.1.1
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange:
    type: ImageChange
