apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: base-16-04
  name: ubuntu-16-04
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: 'ubuntu:16.04'
      name: '16.04'
