- name: Remove Traefik to update it (if Traefik 1 in K3s 1.20 and earlier)
  shell: "kubectl -n kube-system delete helmcharts.helm.cattle.io traefik"
  ignore_errors: yes

- name: Install K3s
  shell: "curl -sfL https://get.k3s.io | sh -"
  args:
    warn: no

- name: Allow the current user to use kubectl command with K3s without sudo
  file:
    path: /home/{{ user }}/.kube
    state: directory
    recurse: yes
    owner: "{{ user }}"

- name: Copy kubctl config
  shell: "bash -c \"kubectl config view --raw\" > /home/{{ user }}/.kube/config"

- name: Change config file ownership and permissions
  file:
    path: /home/{{ user }}/.kube/config
    owner: '{{ user }}'
    mode: '0600'

- name: Use the kubectl config after next login
  lineinfile:
    dest: /home/{{ user }}/.bashrc
    regexp: '^export KUBECONFIG='
    line: export KUBECONFIG=~/.kube/config
