apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: chipster
    name: auth-m2m
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8013
    selector:
      name: auth
    sessionAffinity: None
    type: ClusterIP
