apiVersion: v1
kind: Template
metadata:
  name: chipster-custom-objects
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: auth
    name: auth-m2m
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8013
    selector:
      app: auth
    sessionAffinity: None
    type: ClusterIP
