apiVersion: v1
kind: Template
metadata:
  name: logging${SUBPROJECT_POSTFIX}
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      generation: 1
      labels:
        subproject: ${{SUBPROJECT}}
        app: chipster${SUBPROJECT_POSTFIX}
      name: logstash${SUBPROJECT_POSTFIX}
    spec:
      replicas: 1
      selector:
        name: logstash${SUBPROJECT_POSTFIX}
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        recreateParams:
          timeoutSeconds: 600
        type: Recreate
      template:
        metadata:
          labels:
            subproject: ${{SUBPROJECT}}
            app: chipster${SUBPROJECT_POSTFIX}
            name: logstash${SUBPROJECT_POSTFIX}
        spec:
          containers:
            - image: docker-registry.default.svc:5000/${IMAGE_PROJECT}/logstash
              imagePullPolicy: Always
              name: logstash
              ports:
                - containerPort: 5044
                  name: api
                  protocol: TCP
                - containerPort: 9600
                  name: monitoring-api
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /
                  port: 9600
                  scheme: HTTP
                periodSeconds: 10
                failureThreshold: 3
                successThreshold: 1
                timeoutSeconds: 5
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /usr/share/logstash/data
                  name: data
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: logstash${SUBPROJECT_POSTFIX}
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - logstash
            from:
              kind: ImageStreamTag
              name: logstash:latest
              namespace: ${{IMAGE_PROJECT}}
          type: ImageChange

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        subproject: ${{SUBPROJECT}}
        app: chipster${SUBPROJECT_POSTFIX}
      name: logstash${SUBPROJECT_POSTFIX}
    spec:
      ports:
        - port: 5044
          protocol: TCP
          targetPort: api
      selector:
        name: logstash${SUBPROJECT_POSTFIX}
      sessionAffinity: None
      type: ClusterIP

parameters:
  - name: PROJECT
  - name: IMAGE_PROJECT
  - name: SUBPROJECT
  - name: SUBPROJECT_POSTFIX
