apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: monitoring${SUBPROJECT_POSTFIX}
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:      
      subproject: ${{SUBPROJECT}}
      app: chipster${SUBPROJECT_POSTFIX}
    name: influxdb${SUBPROJECT_POSTFIX}
  spec:
    replicas: 1
    selector:
      name: influxdb${SUBPROJECT_POSTFIX}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          subproject: ${{SUBPROJECT}}
          app: chipster${SUBPROJECT_POSTFIX}
          name: influxdb${SUBPROJECT_POSTFIX}
      spec:
        containers:
        # influxdb2 is very different
        - image: 'influxdb:1.8'
          imagePullPolicy: Always
          name: influxdb
          ports:
          - containerPort: 8086
            name: api
            protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 2
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/influxdb
            name: data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: influxdb${SUBPROJECT_POSTFIX}
    test: false
    triggers:
    - type: ConfigChange
    
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      subproject: ${{SUBPROJECT}}
      app: chipster${SUBPROJECT_POSTFIX}
    name: grafana${SUBPROJECT_POSTFIX}
  spec:
    replicas: 1
    selector:
      name: grafana${SUBPROJECT_POSTFIX}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          subproject: ${{SUBPROJECT}}
          app: chipster${SUBPROJECT_POSTFIX}
          name: grafana${SUBPROJECT_POSTFIX}
      spec:
        containers:
        - image: docker-registry.default.svc:5000/${PROJECT}/grafana
          imagePullPolicy: Always
          name: grafana
          ports:
          - containerPort: 3000
            name: api
            protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 2
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /usr/share/grafana/data
            name: data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grafana${SUBPROJECT_POSTFIX}
    test: false
    triggers:
    - type: ConfigChange
    
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      subproject: ${{SUBPROJECT}}
      app: chipster${SUBPROJECT_POSTFIX}
    name: grafana${SUBPROJECT_POSTFIX}
  spec:
    host: grafana${SUBPROJECT_POSTFIX}-${PROJECT}.${DOMAIN}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: grafana${SUBPROJECT_POSTFIX}
      weight: 100
    wildcardPolicy: None
      
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      subproject: ${{SUBPROJECT}}
      app: chipster${SUBPROJECT_POSTFIX}
    name: influxdb${SUBPROJECT_POSTFIX}
  spec:
    ports:
    - port: 8086
      protocol: TCP
      targetPort: api
    selector:
      name: influxdb${SUBPROJECT_POSTFIX}
    sessionAffinity: None
    type: ClusterIP
    
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      subproject: ${{SUBPROJECT}}
      app: chipster${SUBPROJECT_POSTFIX}
    name: grafana${SUBPROJECT_POSTFIX}
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: api
    selector:
      name: grafana${SUBPROJECT_POSTFIX}
    sessionAffinity: None
    type: ClusterIP

parameters:
- name: PROJECT
- name: DOMAIN
- name: SUBPROJECT
- name: SUBPROJECT_POSTFIX