apiVersion: v1
kind: Template
metadata:
  name: chipster-pvcs
objects:

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: auth-postgres-data
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 100Mi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: auth-security
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 100Mi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: comp-jobs-data
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: comp-jobs-data-mylly
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: db-backups
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 100Mi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: file-broker-storage
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: grafana
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 100Mi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: influxdb
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: job-history-postgres-data
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 100Mi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: session-db-postgres-data
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: tools-bin
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 20Gi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: tools-bin-mylly
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
