apiVersion: v1
kind: Template
metadata:
  name: ${{NAME}}
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ${{NAME}}
  spec:
    parallelism: 1    
    completions: 1    
    template:         
      metadata:
        name: ${{NAME}}
      spec:
        containers:
        - env:
          - name: TOOLS_BIN_VERSION
            value: ${{TOOLS_BIN_VERSION}}
          name: ${{NAME}}
          image: docker-registry.default.svc:5000/${IMAGE_PROJECT}/base
          command: ["bash", "-c", ""]          
          volumeMounts:        
          - mountPath: /mnt/tools
            name: tools-bin
        volumes:
        - name: tools-bin
          persistentVolumeClaim:
            claimName: tools-bin
        restartPolicy: OnFailure
parameters:
- name: IMAGE_PROJECT
- name: TOOLS_BIN_VERSION
- name: NAME
