apiVersion: v1
kind: Template
metadata:
  name: copy-pvc
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: copy-pvc
  spec:
    parallelism: 1    
    completions: 1    
    template:         
      metadata:
        name: copy-pvc
      spec:
        containers:
        - name: copy-pvc
          # image with rsync
          image: docker-registry.default.svc:5000/${IMAGE_PROJECT}/comp-24-04-r-deps
          command: ["bash", "-c", "set -x; set -e; cd /mnt; du -sh *; rm -rf /mnt/destination/lost+found; shopt -s dotglob; if [ -z \"$(ls -A destination)\" ]; then cp -ar source/* destination/; else rsync -a source/* destination/; fi; du -sh *"]
          volumeMounts:        
          - mountPath: /mnt/source
            name: source
          - mountPath: /mnt/destination
            name: destination          
        volumes:
        - name: source
          persistentVolumeClaim:
            claimName: ${{SOURCE_PVC}}
        - name: destination
          persistentVolumeClaim:
            claimName: ${{DESTINATION_PVC}}
        restartPolicy: OnFailure
parameters:
- name: IMAGE_PROJECT
- name: SOURCE_PVC
- name: DESTINATION_PVC