apiVersion: v1
kind: Template
metadata:
  name: download-tools-bin
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: download-tools-bin
  spec:
    parallelism: 1    
    completions: 1    
    template:         
      metadata:
        name: download-tools-bin
      spec:
        containers:
        - name: download-tools-bin
          image: docker-registry.default.svc:5000/${IMAGE_PROJECT}/base
          # Kill other tasks after first error: "--halt 2" in this old 2014 version 
          # of parallel, equals "--halt now,fail=1" in newer versions.
          #
          # Using "set -o pipefail" and "curl --fail" to  fail on curl errors too 
          # and not only based on the exit code of the last "tar" command. Although 
          # tar is quite good in noticing errors too.
          #
          # Downlaod small lz4 packages to local temp file before extraction. At the 
          # moment each lz4 packages contains 1000 small files. When the files
          # are small, it takes too much time to create all files in pipe's 64k buffer
          # causing the server to timeout the idle connection. The packaging process
          # sholud further improved to make sure there are no both large and small files 
          # in the same package, because the current logic will fail in that case.
          #
          command: ["bash", "-c", "set -e; cd /mnt/tools; mkdir -p ${TOOLS_BIN_VERSION}; cd ${TOOLS_BIN_VERSION}; export url='https://object.pouta.csc.fi/swift/v1/AUTH_chipcld/chipster-tools-bin/${TOOLS_BIN_VERSION}/parts'; curl -s $url/files.txt | grep lz4$ | parallel --ungroup -j 8 --halt 2 'set -o pipefail; size=$(curl -sI $url/{} | grep -i Content-Length | cut -d \" \" -f 2 | tr -d \"\r\"); echo $url/{} $size; if [ $size -lt $((5 * 1024 * 1024 * 1024)) ]; then wget --no-verbose --tries 5 $url/{} -O {}_tmp && cat {}_tmp | lz4 -d | tar -x; rm {}_tmp; else curl --silent --show-error --fail $url/{} | lz4 -d | tar -x; fi'"]          
          volumeMounts:        
          - mountPath: /mnt/tools
            name: tools-bin
        volumes:
        - name: tools-bin
          persistentVolumeClaim:
            claimName: tools-bin
        restartPolicy: OnFailure
parameters:
- name: IMAGE_PROJECT
- name: TOOLS_BIN_VERSION