apiVersion: v1
kind: Template
metadata:
  name: ${NAME}
objects:
- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    name: ${{NAME}}
  spec:
    accessModes:
      - "ReadWriteMany"
    resources:
      requests:
        storage: ${{SIZE}}
parameters:
- name: NAME
- name: SIZE
