apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: base-node
  name: base-node
spec:
  output:
    to:
      kind: ImageStreamTag
      name: base-node:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: ""
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: base-24-04:latest
    type: Docker
  triggers:
    - type: ConfigChange
    - imageChange:
      type: ImageChange
