apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: chipster-web-server-js
  name: chipster-web-server-js
spec:
  output:
    to:
      kind: ImageStreamTag
      name: chipster-web-server-js:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: ""
    images:
      - as: null
        from:
          kind: ImageStreamTag
          name: chipster-web-server:latest
        paths:
          - destinationDir: chipster-web-server
            sourcePath: /home/user/chipster-web-server
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: base-node:latest
    type: Docker
  triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: chipster-web-server:latest
      type: ImageChange
    - type: ConfigChange
    - imageChange:
      type: ImageChange
