apiVersion: v1
kind: Template
metadata:
  name: ${NAME}
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      build: cli-client
    name: cli-client
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cli-client:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      dockerfile: ""
      git:
        ref: ${BRANCH}
        uri: https://github.com/chipster/chipster-web-server.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: base-node:latest
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: ${GITHUB_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange:
      type: ImageChange
parameters:
  - name: NAME
  - name: BRANCH
  - name: GITHUB_SECRET
  - name: GENERIC_SECRET