apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: ci-test
  name: ci-test
spec:
  output:
    to:
      kind: ImageStreamTag
      name: ci-test:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: ""
    type: Dockerfile
    images:
      - as: null
        from:
          kind: ImageStreamTag
          name: chipster-web-server:latest
        paths:
          - destinationDir: chipster-web-server
            sourcePath: /home/user/chipster-web-server
      - as: null
        from:
          kind: ImageStreamTag
          name: chipster-tools:latest
        paths:
          - destinationDir: chipster-tools
            sourcePath: /home/user/chipster-tools
      - as: null
        from:
          kind: ImageStreamTag
          name: chipster-web:latest
        paths:
          # add "-app" to the name to separate it from chipster-web-server (to overcome bad parsing in buildconfig-to-docker.bash)
          - destinationDir: chipster-web-app
            sourcePath: /home/user/chipster-web
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: base-ci-test:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
    - imageChange:
      type: ImageChange
    - imageChange:
        from:
          kind: ImageStreamTag
          name: chipster-web-server:latest
    - imageChange:
        from:
          kind: ImageStreamTag
          name: chipster-tools:latest
