apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: comp-24-04-python
  name: comp-24-04-python
spec:
  output:
    to:
      kind: ImageStreamTag
      name: comp-24-04-python:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: ""
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: comp-24-04:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
    - imageChange:
      type: ImageChange
