apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: chipster-web-build
  name: chipster-web-build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: chipster-web-build:latest
  postCommit: {}
  resources:
    limits:
      cpu: 2
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 4Gi
  runPolicy: Serial
  source:
    dockerfile: ""
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: chipster-web:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
    - imageChange:
      type: ImageChange
