apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: filebeat
  name: filebeat
spec:
  output:
    to:
      kind: ImageStreamTag
      name: filebeat:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: ""
    git:
      ref: master
      uri: https://github.com/chipster/chipster-openshift.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: filebeat:7.1.1
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange:
    type: ImageChange
